add workflows
BeanCloudServices/cloud-controller pull request #3
Opened 2023-04-30 11:15 UTC by HieuMinh67

2023-05-01 11:18 UTC, HieuMinh67 commented
GitHub Actions knows which branch to fetch without having input

![image](https://user-images.githubusercontent.com/43398131/235444655-515149e7-d577-44f5-a921-0bfff99bcd9f.png)

2023-05-03 00:47 UTC, binh-le-thanh-mox requested changes
Please rename `.github/workflows/ci.yml`
to `.github/workflows/build-test-push.yml`

2023-05-03 00:47 UTC, binh-le-thanh-mox commented on .github/workflows/ci.yml
> +name: Packer Build
```suggestion
name: Build - Test - Push

```

2023-05-03 00:47 UTC, binh-le-thanh-mox commented on .github/workflows/ci.yml
> +    environment: ${{ needs.branch.outputs.env_name }}
Pushing test AMI to production env does not make any sense

2023-05-03 04:38 UTC, peterbean410 commented on .github/workflows/build-test-push.yml
> +  build:
```suggestion
  build-ami:

```

2023-05-03 08:28 UTC, peterbean410 commented on .github/workflows/build-test-push.yml
> +
```suggestion
```

2023-05-06 02:41 UTC, peterbean410 commented on .github/workflows/build-test-push.yml
> +  test:
```suggestion
  test:
    name: Run Tests
```

2023-05-06 02:41 UTC, peterbean410 commented on .github/workflows/build-test-push.yml
> +    name: Run Tests
```suggestion
    name: Run tests

```

2023-05-06 02:42 UTC, peterbean410 commented on .github/workflows/build-test-push.yml
> +    name: Run tests
```suggestion
    name: Test

```

2023-05-06 02:43 UTC, peterbean410 commented on .github/workflows/build-test-push.yml
> +    name: Packer Build
```suggestion
    name: Build AMI

```

2023-05-08 10:47 UTC, merged